apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8slogbck-agent
  namespace: k8slogbck
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8slogbck-role
rules:
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8slogbck-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8slogbck-role
subjects:
- kind: ServiceAccount
  name: k8slogbck-agent
  namespace: k8slogbck
