apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-backup-sa
  namespace: backup-jobs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: log-backup-role
rules:
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: log-backup-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: log-backup-role
subjects:
- kind: ServiceAccount
  name: log-backup-sa
  namespace: backup-jobs
